trigger:
- master

jobs:
- job:
  displayName: "Build"
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - script: |
      sudo npm install -g typescript
    displayName: "Install Typescript"
  - script: |
      chmod +x ./build.sh
      ./build.sh
    displayName: "Run build"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "./publish"
      ArtifactName: "Homepage"
    displayName: "Publish all"
