
baseurl = "https://capra314cabra.github.io"
title = "Capra Cabra Notes"

theme = "hugo-coder"

languagecode = "ja"
defaultcontentlanguage = "ja"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableGitInfo = true

enableRobotsTXT = true

[markup.goldmark.renderer]
    unsafe= true

[params]
    author = "capra314cabra"
    description = "This is a capra314cabra's blog and have a lot of contents about programming."
    keywords = "capra314cabra,programming,プログラミング,c#,developer,note,blog,personal"
    info = "Wanna be a developer improving our lives."
    avatarurl = "/images/capra314cabra.jpg"
    footercontent = "Wanna be a developer improving our lives."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/capra314cabra/capra314cabra.github.io/tree/master"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    favicon_16 = "images/logo/favicon-16x16.png"
    favicon_32 = "images/logo/favicon-32x32.png"

    # Custom CSS
    custom_css = ["https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/vs2015.min.css"]

    # Custom JS
    custom_js = ["https://cdn.jsdelivr.net/npm/gist-embed@1.0.3/dist/gist-embed.min.js", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/all.min.js"]

[params.utteranc]
    repo = "capra314cabra/capra314cabra.github.io"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[params.social]]
    name = "Github"
    icon = "icon fab fa-github"
    weight = 1
    url = "https://github.com/capra314cabra/"
[[params.social]]
    name = "Medium"
    icon = "icon fab fa-medium"
    weight = 2
    url = "https://medium.com/@capra314cabra"
[[params.social]]
    name = "RSS"
    icon = "icon fas fa-rss"
    weight = 3
    url = "https://capra314cabra.github.io/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Games"
            weight = 3
            url = "games/"

            [[languages.en.menu.main]]
            name = "Tags"
            weight = 4
            url = "tags/"
            [[languages.en.menu.main]]
            name = "GitHub"
            weight = 5
            url = "https://github.com/capra314cabra"


    [languages.ja]
        languagename = "日本語"
        title = "Capra Cabra Notes"

        [languages.ja.menu]

            [[languages.ja.menu.main]]
            name = "About"
            weight = 1
            url = "/"

            [[languages.ja.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.ja.menu.main]]
            name = "Games"
            weight = 3
            url = "games/"

            [[languages.ja.menu.main]]
            name = "Tags"
            weight = 4
            url = "tags/"

            [[languages.ja.menu.main]]
            name = "GitHub"
            weight = 5
            url = "https://github.com/capra314cabra"
